"""Initial migration

Revision ID: 22295489a0c1
Revises: 
Create Date: 2025-05-28 15:25:48.506040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22295489a0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('student_email', sa.String(length=100), nullable=True),
    sa.Column('discipline', sa.String(length=50), nullable=True),
    sa.Column('class_number', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('printer', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=32), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('time_hours', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('acknowledged_minimum_charge', sa.Boolean(), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=True),
    sa.Column('student_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_token', sa.String(length=128), nullable=True),
    sa.Column('confirm_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reject_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_token')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('job')
    # ### end Alembic commands ###
