/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/templates/**/*.html",
    "./app/static/**/*.js",
  ],
  safelist: [
    // Ensure our Apple components are always included
    'btn-apple-primary',
    'btn-apple-destructive', 
    'btn-apple-secondary',
    'btn-apple-text',
    'input-apple',
    'select-apple',
    'label-apple',
    'card-apple',
    'card-apple-glass',
    'nav-apple',
    'alert-apple',
    'alert-apple-warning',
    'alert-apple-error',
    'alert-apple-success',
    'form-group-apple',
    'glass',
    'glass-dark',
    'glass-strong',
    'touch-target',
    'touch-target-lg',
    'text-apple-large-title',
    'text-apple-title1',
    'text-apple-title2',
    'text-apple-title3',
    'text-apple-headline',
    'text-apple-body',
    'text-apple-callout',
    'text-apple-footnote',
    'space-apple-xs',
    'space-apple-sm',
    'space-apple',
    'space-apple-md',
    'space-apple-lg',
    'space-apple-xl',

    // V0.dev color system classes
    'btn-v0-primary',
    'btn-v0-secondary',
    'btn-v0-success',
    'btn-v0-danger',
    'btn-v0-warning',
    'card-v0',
    'badge-v0-new',
    'badge-v0-status',
    'tab-v0-active',
    'tab-v0-inactive',
    'input-v0',
    'text-v0-primary',
    'text-v0-secondary',
    'text-v0-muted',
    'bg-v0-background',
    'bg-v0-card',
    'border-v0-border',
    // Status colors for job age
    'text-v0-green-600',
    'text-v0-yellow-600', 
    'text-v0-orange-600',
    'text-v0-red-600',
    // Action button colors
    'bg-v0-blue-100',
    'text-v0-blue-700',
    'bg-v0-green-100',
    'text-v0-green-700',
    'bg-v0-red-100',
    'text-v0-red-700',
    'bg-v0-purple-100',
    'text-v0-purple-700',
    'bg-v0-orange-100',
    'text-v0-orange-800',

    // V0.dev typography classes
    'font-v0-sans',
    'font-v0-mono',
    'text-v0-xs',
    'text-v0-sm',
    'text-v0-base',
    'text-v0-lg',
    'text-v0-xl',
    'text-v0-2xl',
    'text-v0-3xl',
    'text-v0-button',
    'text-v0-tab',
    'text-v0-badge',
    'text-v0-detail',
    'text-v0-label',
    'text-v0-dashboard-title',
    'text-v0-job-title',
    'text-v0-body',

    // V0.dev spacing and layout classes
    'spacing-v0-xs',
    'spacing-v0-sm',
    'spacing-v0-base',
    'spacing-v0-md',
    'spacing-v0-lg',
    'spacing-v0-xl',
    'spacing-v0-2xl',
    'spacing-v0-3xl',
    'container-v0',
    'container-v0-page',
    'grid-v0-jobs',
    'grid-v0-details',
    'section-v0',
    'card-section-v0',
    'button-group-v0',
    'tabs-v0',
    'header-v0',
    'header-actions-v0',
    'job-card-v0',
    'job-card-content-v0',
    'job-card-actions-v0',

    // V0.dev utility spacing classes
    'p-v0-xs',
    'p-v0-sm',
    'p-v0-base',
    'p-v0-md',
    'p-v0-lg',
    'p-v0-xl',
    'p-v0-2xl',
    'm-v0-xs',
    'm-v0-sm',
    'm-v0-base',
    'm-v0-md',
    'm-v0-lg',
    'm-v0-xl',
    'm-v0-2xl',
    'gap-v0-xs',
    'gap-v0-sm',
    'gap-v0-base',
    'gap-v0-md',
    'gap-v0-lg',
    'gap-v0-xl',
    'gap-v0-2xl'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // Extend default theme without conflicts
      colors: {
        // Use CSS variables for dynamic theming
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)', 
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
      },
      spacing: {
        // Match our design system spacing
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)', 
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
      },
      zIndex: {
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'toast': 'var(--z-toast)',
        'tooltip': 'var(--z-tooltip)',
      }
    },
  },
  plugins: [
    // Remove conflicting plugins to avoid component system conflicts
    // Our custom component system handles forms and typography
  ],
  corePlugins: {
    // Keep preflight but customize
    preflight: true,
  },
  // Ensure compatibility with our custom CSS architecture
  important: false, // Don't force !important on all utilities
} 